apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  cdn:
    enabled: {{ .Values.BackendConfig.isCDNEnable }}
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
