apiVersion: v1
kind: Service
metadata:
  name: {{ include "imageChart.fullname" . }}
  labels:
    {{- include "imageChart.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "imageChart.selectorLabels" . | nindent 4 }}
